DROP TABLE IF EXISTS TOURNAMENT;
 
CREATE TABLE TOURNAMENT (
  id BIGINT PRIMARY KEY,
  code VARCHAR(255) NOT NULL,
  name VARCHAR(250) NOT NULL,
  tournament_type VARCHAR(250) NOT NULL,
  tournament_modality VARCHAR(250) NOT NULL,
  referee_name VARCHAR(250) NOT NULL,
  game_formula VARCHAR(250) NOT NULL,
  site VARCHAR(255),
  times INT,
  boards INT,
  bonus BOOLEAN,
  date_creation DATE NOT NULL
);

DROP SEQUENCE IF EXISTS TOURNAMENT_SEQ;

CREATE SEQUENCE TOURNAMENT_SEQ;

CREATE TABLE TOURNAMENT_PARTECIPANT (
	id BIGINT PRIMARY KEY,
	nominative  VARCHAR(255) NOT NULL,
	email VARCHAR(255)
);

CREATE SEQUENCE TOURNAMENT_PARTECIPIANT_SEQ;

CREATE TABLE TEAM (
	id BIGINT PRIMARY KEY,
	tournament_id INT NOT NULL,
 	code VARCHAR(255) NOT NULL,
 	type VARCHAR(255) NOT NULL
);
ALTER TABLE TEAM ADD FOREIGN KEY ( tournament_id) REFERENCES TOURNAMENT( id ) ;


CREATE SEQUENCE TEAM_SEQ;
